// router_docs_test.go — unit tests for the uncovered branch in
// registerDocsRoutes (router.go lines 260-270):
//
//	stdSwagger := ginSwagger.WrapHandler(swaggerFiles.Handler)
//	r.GET("/swagger/*any", secHeaders, authMiddleware, func(c *gin.Context) {
//	    switch {
//	    case strings.HasSuffix(c.Request.URL.Path, "/index.css"):
//	        SwaggerThemeHandler(c)
//	    case strings.HasSuffix(c.Request.URL.Path, "/swagger-initializer.js"):
//	        SwaggerInitializerHandler(c)
//	    default:
//	        stdSwagger(c)   ← this line
//	    }
//	})
//
// The CSS and initializer-JS branches are already covered by
// TestRegisterDocsRoutes_SwaggerCSS_ServedByThemeHandler and
// TestRegisterDocsRoutes_SwaggerInitializerJS_ServedByInitHandler in
// coverage_gaps_test.go. This file adds the `default: stdSwagger(c)` branch
// by requesting /swagger/doc.json — a URL that ends neither in /index.css
// nor /swagger-initializer.js, so the switch falls through to stdSwagger.
//
// The /asyncapi.yaml route is also not covered by existing tests; it is added
// here for completeness.
package http

import (
	"context"
	"net/http"
	"net/http/httptest"
	"testing"

	"github.com/gin-gonic/gin"
	"github.com/stretchr/testify/assert"
)

// TestRegisterDocsRoutes_SwaggerDocJson_HitsDefaultBranch verifies that a
// GET /swagger/doc.json request falls through to the `default: stdSwagger(c)`
// branch in the /swagger/*any handler, bypassing both the index.css and the
// swagger-initializer.js special cases.
//
// The secHeaders middleware (registered before the switch) sets X-Frame-Options
// on every /swagger/* response. Its presence confirms the route was registered
// and the middleware chain ran — even when ginSwagger returns 404 in test mode
// because no swagger spec has been generated (docs are generated by `make swag`,
// which is not run in unit tests).
//
// Contrast: an unregistered path produces no X-Frame-Options header.
func TestRegisterDocsRoutes_SwaggerDocJson_HitsDefaultBranch(t *testing.T) {
	gin.SetMode(gin.TestMode)
	r := gin.New()
	cfg := RouterConfig{
		Docs: DocsConfig{
			Environment: "dev",
			Enabled:     true,
		},
	}
	registerDocsRoutes(r, cfg)

	// /swagger/doc.json — ends in neither /index.css nor /swagger-initializer.js,
	// so the switch default branch (stdSwagger) runs.
	w := httptest.NewRecorder()
	req, _ := http.NewRequestWithContext(
		context.Background(), http.MethodGet, "/swagger/doc.json", nil,
	)
	r.ServeHTTP(w, req)

	// secHeaders sets X-Frame-Options on every matched /swagger/* route.
	// Its presence proves the route was matched and the handler chain ran.
	assert.Equal(t, "DENY", w.Header().Get("X-Frame-Options"),
		"/swagger/doc.json must set X-Frame-Options, proving secHeaders + default branch ran")
	assert.NotEqual(t, http.StatusUnauthorized, w.Code,
		"/swagger/doc.json must not require auth in non-production")
}

// TestRegisterDocsRoutes_AsyncAPIYAML_RouteExists verifies that the
// /asyncapi.yaml route is registered and reachable in non-production.
// The AsyncAPIYAMLHandler serves the embedded YAML spec; any 2xx response
// confirms the route exists and the handler ran.
func TestRegisterDocsRoutes_AsyncAPIYAML_RouteExists(t *testing.T) {
	gin.SetMode(gin.TestMode)
	r := gin.New()
	cfg := RouterConfig{
		Docs: DocsConfig{
			Environment: "staging",
			Enabled:     false, // active() returns true outside production
		},
	}
	registerDocsRoutes(r, cfg)

	w := httptest.NewRecorder()
	req, _ := http.NewRequestWithContext(
		context.Background(), http.MethodGet, "/asyncapi.yaml", nil,
	)
	r.ServeHTTP(w, req)

	// Route must be registered (not 404).
	assert.NotEqual(t, http.StatusNotFound, w.Code,
		"/asyncapi.yaml must be registered in non-production environments")
}

// TestRegisterDocsRoutes_SwaggerDocJson_ProductionWithToken_BlocksUnauth
// verifies that the default stdSwagger branch is also protected by the
// production auth middleware: a request to /swagger/doc.json without the
// correct token returns 401, not 200.
func TestRegisterDocsRoutes_SwaggerDocJson_ProductionWithToken_BlocksUnauth(t *testing.T) {
	gin.SetMode(gin.TestMode)
	r := gin.New()
	cfg := RouterConfig{
		Docs: DocsConfig{
			Environment: "production",
			Enabled:     true,
			AuthToken:   "my-secret",
		},
	}
	registerDocsRoutes(r, cfg)

	w := httptest.NewRecorder()
	req, _ := http.NewRequestWithContext(
		context.Background(), http.MethodGet, "/swagger/doc.json", nil,
	)
	r.ServeHTTP(w, req)

	assert.Equal(t, http.StatusUnauthorized, w.Code,
		"production /swagger/doc.json without auth must return 401")
}

// TestRegisterDocsRoutes_SwaggerDocJson_ProductionWithToken_AllowsValidToken
// verifies that the correct Bearer token lets a /swagger/doc.json request pass
// the auth middleware and reach stdSwagger.  The X-Frame-Options header set by
// secHeaders confirms the full middleware chain ran (secHeaders → authMiddleware
// → handler switch → default branch).
func TestRegisterDocsRoutes_SwaggerDocJson_ProductionWithToken_AllowsValidToken(t *testing.T) {
	gin.SetMode(gin.TestMode)
	r := gin.New()
	cfg := RouterConfig{
		Docs: DocsConfig{
			Environment: "production",
			Enabled:     true,
			AuthToken:   "my-secret",
		},
	}
	registerDocsRoutes(r, cfg)

	w := httptest.NewRecorder()
	req, _ := http.NewRequestWithContext(
		context.Background(), http.MethodGet, "/swagger/doc.json", nil,
	)
	req.Header.Set("Authorization", "Bearer my-secret")
	r.ServeHTTP(w, req)

	// Auth passed; secHeaders set X-Frame-Options; stdSwagger ran.
	assert.NotEqual(t, http.StatusUnauthorized, w.Code,
		"valid token must pass production auth on /swagger/doc.json")
	assert.Equal(t, "DENY", w.Header().Get("X-Frame-Options"),
		"X-Frame-Options must be set, confirming secHeaders and the default branch ran")
}
