#!/usr/bin/env python3
"""
Post-process the swagger files generated by `make swag` to inject a top-level
`tags` array (swaggo's `@tag.name`/`@tag.description` annotations are parsed
but not emitted to the spec — this script is the single source of truth for
tag order and description).

Swagger UI groups operations by the tag they carry; without a top-level
`tags` array the order falls back to first-appearance-in-paths, which
surfaces unrelated groups above the core internal/operator/tenant groups.
Declaring the tags at the root pins the display order.

Run: python3 scripts/patch-swagger-extensions.py
     (called automatically by `make swag`)

Idempotent: an existing top-level `tags:` block is replaced in-place.
"""

import json
import sys
from pathlib import Path

ROOT = Path(__file__).parent.parent

# ---------------------------------------------------------------------------
# Tag order — edit here, re-run `make swag` to propagate.
# Order mirrors cmd/server/swagger_info.go so the two never drift.
# ---------------------------------------------------------------------------

TAGS = [
    {"name": "internal",    "description": "In-mesh service-to-service (I-1..I-15)"},
    {"name": "operator",    "description": "Platform operator (O-4, O-7 — O-1/O-2/O-3/O-5/O-6 retired ADR-0007 Wave 1, moved to iam-catalog-admin)"},
    {"name": "tenant",      "description": "Tenant CRUD (P-1, P-2)"},
    {"name": "departments", "description": "Department activation (P-3, P-9, P-10, P-11, P-24, P-25)"},
    {"name": "members",     "description": "Membership management (P-4..P-8, P-27, P-28)"},
    {"name": "roles",       "description": "Dept-role labels (P-12, P-13)"},
    {"name": "invitations", "description": "Two-step invite→accept (P-6, P-30, P-31)"},
    {"name": "resolution",  "description": "Removal-resolution (P-26)"},
    {"name": "infra",       "description": "Health & metrics (unauthenticated)"},
]


# ---------------------------------------------------------------------------
# Patch swagger.json
# ---------------------------------------------------------------------------

def patch_json(path: Path) -> None:
    spec = json.loads(path.read_text())
    spec.pop("tags", None)
    # Insert the tags block right before securityDefinitions for readability.
    ordered = {}
    for key, val in spec.items():
        if key == "securityDefinitions":
            ordered["tags"] = TAGS
        ordered[key] = val
    if "tags" not in ordered:
        ordered["tags"] = TAGS  # fallback if securityDefinitions is absent
    path.write_text(json.dumps(ordered, indent=4, ensure_ascii=False) + "\n")
    print(f"  patched {path.relative_to(ROOT)}")


# ---------------------------------------------------------------------------
# Patch swagger.yaml  (line-based insertion — avoids PyYAML dep)
# ---------------------------------------------------------------------------

def patch_yaml(path: Path) -> None:
    lines = path.read_text().splitlines()
    # Strip any existing top-level `tags:` block.
    cleaned: list[str] = []
    skip = False
    for line in lines:
        if line.startswith("tags:"):
            skip = True
            continue
        if skip:
            # Top-level block ends when we hit another top-level key (a non-
            # indented line that isn't blank).
            if line and not line.startswith(" ") and not line.startswith("-"):
                skip = False
            else:
                continue
        cleaned.append(line)

    # Assemble the tags block.
    tag_lines = ["tags:"]
    for t in TAGS:
        tag_lines.append(f"- description: {_yaml_scalar(t['description'])}")
        tag_lines.append(f"  name: {t['name']}")

    # Insert just before `securityDefinitions:` for consistency with JSON.
    insert_at = next(
        (i for i, l in enumerate(cleaned) if l.startswith("securityDefinitions:")),
        len(cleaned),
    )
    result = cleaned[:insert_at] + tag_lines + cleaned[insert_at:]
    path.write_text("\n".join(result) + "\n")
    print(f"  patched {path.relative_to(ROOT)}")


def _yaml_scalar(v) -> str:
    s = str(v)
    needs_quote = any(c in s for c in (':', '#', '[', ']', '{', '}', '&', '*', '!', '|', '>', "'", '"', '%', '@', '`', '\n'))
    if needs_quote:
        return '"' + s.replace('"', '\\"') + '"'
    return s


# ---------------------------------------------------------------------------
# Patch docs.go  (JSON is embedded as a raw template string)
# ---------------------------------------------------------------------------

def patch_docs_go(path: Path) -> None:
    text = path.read_text()
    anchor = '"swagger": "2.0",'
    if anchor not in text:
        print(f"  WARN: anchor not found in {path.relative_to(ROOT)}, skipping", file=sys.stderr)
        return

    # Strip any previously injected tags block.
    lines = text.splitlines()
    cleaned_lines: list[str] = []
    in_tags = False
    for line in lines:
        if line.startswith('    "tags":'):
            in_tags = True
            continue
        if in_tags:
            # End of the block is a line starting with 4 spaces + "\"key\":"
            # that isn't part of the array structure.
            stripped = line.lstrip()
            if stripped.startswith('"') and line.startswith('    "') and not (
                stripped.startswith('"name":') or stripped.startswith('"description":')
            ):
                in_tags = False
            elif line.strip() in {"", "],"} or line.startswith("        "):
                # Still inside — either continuation of array or blank
                if line.strip() == "],":
                    in_tags = False
                    continue
                continue
            else:
                in_tags = False
        if not in_tags:
            cleaned_lines.append(line)

    cleaned = "\n".join(cleaned_lines)

    # Serialise the tags block with the same 4-space indent swaggo uses.
    tags_json = json.dumps(TAGS, indent=4, ensure_ascii=False)
    indented = "\n".join("    " + l for l in tags_json.splitlines())
    fragment = f'    "tags": {indented.lstrip()},'

    patched = cleaned.replace(
        f'    {anchor}',
        f'    {anchor}\n{fragment}',
        1,
    )
    if not patched.endswith("\n"):
        patched += "\n"
    path.write_text(patched)
    print(f"  patched {path.relative_to(ROOT)}")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    print("Patching swagger tag order...")
    patch_json(ROOT / "docs/swagger/swagger.json")
    patch_yaml(ROOT / "docs/swagger/swagger.yaml")
    patch_docs_go(ROOT / "docs/swagger/docs.go")
    print("Done.")
